// 场景模板配置
import {
  Newspaper,
  TrendingUp,
  Monitor,
  Rss,
  GitFork,
  Send,
  Globe,
  ChartColumn,
  Mail,
  DollarSign,
  Mic,
  Smartphone,
  FileText,
  Calendar,
  Languages,
} from 'lucide-react'
import type { ScenarioTemplate } from '../types/workflow'

export const SCENARIO_TEMPLATES: ScenarioTemplate[] = [
  {
    key: 'news',
    title: '每日新闻摘要推送',
    description: '抓取新闻 → 生成摘要 → 推送微信',
    requirement: '每天早上8点抓取科技新闻生成摘要推送到微信',
    icon: Newspaper,
    category: '新闻资讯',
  },
  {
    key: 'sales',
    title: '销售数据报表生成',
    description: '查询数据 → 生成图表 → 邮件发送',
    requirement: '每周一从数据库导出销售数据生成可视化报表邮件发给团队',
    icon: TrendingUp,
    category: '销售报表',
  },
  {
    key: 'review',
    title: '代码提交 Code Review',
    description: '获取提交 → AI Review → Slack 推送',
    requirement: '每次代码提交后自动进行code review把问题发到slack',
    icon: Monitor,
    category: '开发运维',
  },
  {
    key: 'rss',
    title: 'RSS 订阅聚合',
    description: '聚合 RSS 源，AI 生成摘要，邮件推送',
    requirement: '聚合多个RSS订阅源用AI生成摘要并通过邮件推送给我',
    icon: Rss,
    category: '新闻资讯',
  },
  {
    key: 'github',
    title: 'GitHub Issue 监控',
    description: '定时检查 GitHub 新 Issue，Slack 推送通知',
    requirement: '每天定时检查GitHub仓库的新Issue有新的就推送到Slack',
    icon: GitFork,
    category: '开发运维',
  },
  {
    key: 'telegram',
    title: 'Telegram 推送',
    description: '定时 AI 生成内容，Telegram 推送',
    requirement: '每天定时用AI生成今日资讯摘要并推送到Telegram',
    icon: Send,
    category: '通讯推送',
  },
  {
    key: 'webmonitor',
    title: '网页监控告警',
    description: '定时抓取网页，关键词触发企业微信告警',
    requirement: '定时抓取指定网页内容命中关键词时通过企业微信告警',
    icon: Globe,
    category: '监控告警',
  },
  {
    key: 'data',
    title: '数据分析报告',
    description: '读取数据文件，清洗分析，生成报告',
    requirement: '读取本地销售数据文件清洗分析后生成数据报告',
    icon: ChartColumn,
    category: '数据分析',
  },
  {
    key: 'email_reply',
    title: '邮件自动回复',
    description: '邮件触发 → AI 生成回复 → 发送',
    requirement: '收到邮件时用AI自动生成礼貌回复并发送',
    icon: Mail,
    category: '通讯推送',
  },
  {
    key: 'price_monitor',
    title: '竞品价格监控',
    description: '定时抓取 → 价格对比 → 告警',
    requirement: '每天定时抓取竞品商品页面价格变化超过10%时通过企业微信告警',
    icon: DollarSign,
    category: '监控告警',
  },
  {
    key: 'meeting_notes',
    title: '会议纪要生成',
    description: '上传文件 → 转写 → AI 总结 → 邮件',
    requirement: '上传会议录音文件转写后用AI生成结构化会议纪要并发送邮件',
    icon: Mic,
    category: '数据分析',
  },
  {
    key: 'social_content',
    title: '社媒内容生成',
    description: '主题输入 → AI 生成多平台文案 → 批量发布',
    requirement: '输入主题用AI生成适合微信公众号微博小红书的多平台文案',
    icon: Smartphone,
    category: '通讯推送',
  },
  {
    key: 'feedback_analysis',
    title: '客户反馈分析',
    description: '聚合反馈 → 情感分析 → 生成报告',
    requirement: '聚合多个渠道的客户反馈用AI做情感分析生成周报',
    icon: FileText,
    category: '数据分析',
  },
  {
    key: 'schedule_reminder',
    title: '日程提醒',
    description: '定时读取日历 → AI 生成提醒 → 推送',
    requirement: '每天早上读取今日日程用AI生成提醒事项推送到微信',
    icon: Calendar,
    category: '通讯推送',
  },
  {
    key: 'doc_translate',
    title: '文档翻译',
    description: '上传文档 → 翻译 → 保存 + 邮件',
    requirement: '上传文档自动翻译成英文保存并发送邮件通知',
    icon: Languages,
    category: '数据分析',
  },
]
